In [1]:
import numpy as np
import pandas as pd
from libreco.data import DatasetPure
from libreco.algorithms import NCF
from libreco.evaluation import evaluate
from libreco.data import random_split, DatasetPure

WARNING:tensorflow:From e:\Repos\Book-recommender-system\venv\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

### BOOKS

In [2]:
data = pd.read_csv('../data/merged_final_dataset.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      10000 non-null  int64
 1   ISBN         10000 non-null  int64
 2   Book-Rating  10000 non-null  int64
 3   Book-Title   10000 non-null  object
dtypes: int64(3), object(1)
memory usage: 312.6+ KB

In [4]:
data.head(4)

   User-ID        ISBN  Book-Rating                               Book-Title
0        8   887841740            5                       The Middle Stories
1        8    74322678            5  Where You'll Find Me: And Other Stories
2        8  1881320189            7            Goodbye to the Buttermilk Sky
3        8     2005018            5                             Clara Callan

In [5]:
new_data = data.rename(columns={'User-ID': 'user', 'ISBN': 'item', 'Book-Rating': 'label'})

In [6]:
new_data.head()

   user        item  label                                    Book-Title
0     8   887841740      5                            The Middle Stories
1     8    74322678      5       Where You'll Find Me: And Other Stories
2     8  1881320189      7                 Goodbye to the Buttermilk Sky
3     8     2005018      5                                  Clara Callan
4     8  1567407781      6  The Witchfinder (Amos Walker Mystery Series)

In [7]:
train_data, eval_data, test_data = random_split(new_data, multi_ratios=[0.8, 0.1, 0.1])

In [8]:
train_data, data_info= DatasetPure.build_trainset(train_data)
eval_data = DatasetPure.build_evalset(eval_data)
test_data = DatasetPure.build_testset(test_data)

In [9]:
print(train_data)

<libreco.data.transformed.TransformedSet object at 0x000001F20C1729E0>

In [10]:
ncf = NCF(
    task="rating",
    data_info=data_info,
    loss_type="cross_entropy",
    embed_size=16,
    n_epochs=10,
    lr=1e-3,
    batch_size=2048,
    num_neg=1,
)

In [11]:
# monitor metrics on eval data during training
ncf.fit(
    train_data,
    neg_sampling=False, #for rating, this param is false else True
    verbose=2,
    eval_data=eval_data,
    metrics=["rmse", "mae"],
    # You can add more metrics as needed
    )

# do final evaluation on test data
evaluate(
    model=ncf,
    data=test_data,
    neg_sampling=False,
    metrics=["rmse", "mae"],
    )

Training start time: 2026-02-28 22:20:36
WARNING:tensorflow:From e:\Repos\Book-recommender-system\venv\lib\site-packages\keras\layers\normalization\batch_normalization.py:561: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

e:\Repos\Book-recommender-system\venv\lib\site-packages\libreco\layers\dense.py:31: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  net = tf.layers.batch_normalization(net, training=is_training)
2026-02-28 22:20:36,333 - WARNING - From e:\Repos\Book-recommender-system\venv\lib\site-packages\keras\layers\normalization\batch_normalization.py:561: _colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
e:\Repos\Book-recommender-system\venv\lib\site-packages\libreco\layers\dense.py:39: UserWarning: `tf.layers.batch_normalization` is deprecated and will be removed in a future version. Please use `tf.keras.layers.BatchNormalization` instead. In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.BatchNormalization` documentation).
  net = tf.layers.batch_normalization(net, training=is_training)
train: 100%|██████████| 8/8 [00:00<00:00, 22.08it/s]

Epoch 1 elapsed: 0.366s
	 train_loss: 63.0803

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]

	 eval rmse: 7.0909
	 eval mae: 6.8902
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 151.27it/s]

Epoch 2 elapsed: 0.057s
	 train_loss: 60.1953

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 1767.51it/s]

	 eval rmse: 7.0909
	 eval mae: 6.8902
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 126.64it/s]

Epoch 3 elapsed: 0.067s
	 train_loss: 57.4651

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 332.14it/s]

	 eval rmse: 7.0909
	 eval mae: 6.8902
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 111.46it/s]

Epoch 4 elapsed: 0.077s
	 train_loss: 53.9765

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 986.90it/s]

	 eval rmse: 7.0909
	 eval mae: 6.8902
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 105.58it/s]

Epoch 5 elapsed: 0.082s
	 train_loss: 49.5613

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 492.17it/s]

	 eval rmse: 6.9258
	 eval mae: 6.7216
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 108.10it/s]

Epoch 6 elapsed: 0.078s
	 train_loss: 43.9114

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 500.16it/s]

	 eval rmse: 6.3847
	 eval mae: 6.1669
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 122.40it/s]

Epoch 7 elapsed: 0.071s
	 train_loss: 36.8747

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 332.59it/s]

	 eval rmse: 5.7020
	 eval mae: 5.4656
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 109.20it/s]

Epoch 8 elapsed: 0.078s
	 train_loss: 28.6301

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 394.98it/s]

	 eval rmse: 4.8582
	 eval mae: 4.6014
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 105.13it/s]

Epoch 9 elapsed: 0.081s
	 train_loss: 19.7741

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 497.43it/s]

	 eval rmse: 3.8122
	 eval mae: 3.5247
==============================

train: 100%|██████████| 8/8 [00:00<00:00, 105.23it/s]

Epoch 10 elapsed: 0.083s
	 train_loss: 11.4612

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 500.04it/s]

	 eval rmse: 2.7400
	 eval mae: 2.4228
==============================

eval_pointwise: 100%|██████████| 1/1 [00:00<00:00, 999.12it/s]

{'rmse': 2.6866242932527036, 'mae': 2.3534809565214516}

In [12]:
top_10_item_ids = ncf.recommend_user(user=14, n_rec=10)

top_3_titles = new_data[new_data['item'].isin(top_10_item_ids[14])]['Book-Title'].values[:6]
print(top_3_titles)

['Barrel Fever : Stories and Essays (Barrel Fever)' 'Hannibal'
 "Kingmaker's Sword (The Rune Blade Trilogy, Book 1)" 'Southern Cross'
 'Ein gutes Jahr.'
 "The White Dog Cafe Cookbook: Recipes and Tales of Adventure from Philadelphia's Revolutionary Restaurant"]

In [13]:
# unique users
unique_user_ids = data['User-ID'].unique()

print("Some unique user IDs:", unique_user_ids[:10])

Some unique user IDs: [ 8  9 12 14 16 17 19 22 26 32]